
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # Tell Netlify to ignore VITE_ prefixed variables during secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "VITE_GITHUB_APP_ID,VITE_GITHUB_APP_INSTALLATION_ID"

